### ISSUE TITLE
Setup CI with Travis 

### ISSUE THREAD

**Issue by tiberiu-biking** [SpringBatchDashboard/spring-batch-dashboard#2]
Link the repository with Travis CI and set up the build script.

**Comment by sziolkow** [comment]
On the travis server configuration looks like this:
{
  "language": "java",
  "jdk": "oraclejdk8",
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}

but in the repository we have:
language: java

jdk:
  - oraclejdk8

I'm not quite sure if this is ok ...

**Comment by tiberiu-biking** [comment]
That seems to be the Travis configuration.

**Comment by sziolkow** [comment]
Ok, than nothing to do there. I'll close it.
